### PR TITLE
Get state_class working for sensors

### PR DESCRIPTION
**Pull request by feibeck**
In order to get the state_class attribute working. Seems like
this needs a SensorEntity instead of an Entity.

### CODE REVIEW

**Comment by Bouni** [comment]
It seems that your PR at least brought the `state_class` attribute to show up in the Developer tools:

image

**Comment by feibeck** [comment]
I did not have time to look at this yet. Maybe I'll invest some time over the weekend…

**Comment by Bouni** [comment]
> I did not have time to look at this yet. Maybe I'll invest some time over the weekend…

No need to hurry, I don't have much time either, just to many side projects :nerd_face:

**Comment by feibeck** [comment]
Yeah, but now that I have the integration running I want to have some of the data available with statistics :-D

**Comment by Bouni** [comment]
I've merged this as it dows not do any harm.

**Comment by feibeck** [comment]
👍

**Comment by Dididam** [comment]
Hi could you give an update if the statistics is working now? I tried with 01.30 and added the state_class to my config but it's not available on the statistics card.

**Pull request merged**
